services:
  redis:
    image: redis:alpine
    container_name: local-redis-kv
    ports:
      - "6379:6379"

  mailcatcher:
    image: sj26/mailcatcher
    container_name: local-mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
